### ISSUE TITLE
remotes

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [afsc-assessments/funplots#1]
Note that this method is not quite correct. This will work if you have already installed afscdata on your machine but it won't work as a standalone R package. https://github.com/afsc-assessments/funplots/blob/4bb66d89d3cef2e10081f35b77755223c44138e7/DESCRIPTION#L14

A way to have a complete package is to add `Remotes: github::afsc-assessments/afscdata` to your DESCRIPTION file (and remove afscdata from the `Imports:` section).

**Comment by careymcg** [comment]
This was changed according to the suggestion in commit dda67a1f070b452330f7ebd90c41d2090b96b641.
